---
name: 'PR Triage Board Bot'
description: 'A GitHub Action to manage a GitHub Project board for PR triage'
author: 'yuvipanda'
branding:
  icon: 'list'
  color: 'blue'

inputs:
  organization:
    description: 'GitHub organization name'
    required: true
  project-number:
    description: 'GitHub Project board number'
    required: true
  gh-app-id:
    description: 'GitHub App ID for authentication'
    required: true
  gh-app-installation-id:
    description: 'GitHub App Installation ID for authentication'
    required: true
  gh-app-private-key:
    description: 'GitHub App private key (PEM format) for authentication'
    required: true
  repositories:
    description: >
      Comma-separated list of repository names to limit querying to
      (optional). Example: repo1,repo2,repo3
    required: false
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '23.x'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        cache: 'npm'
        node-version: ${{ inputs.node-version }}

    - name: Install dependencies
      run: npm ci
      shell: bash
      working-directory: ${{ github.action_path }}

    - name: Build project
      run: npm run build
      shell: bash
      working-directory: ${{ github.action_path }}

    - name: Setup GitHub App Private Key
      run: |
        echo "${{ inputs.gh-app-private-key }}" > private-key.pem
      shell: bash
      working-directory: ${{ github.action_path }}

    - name: Run PR Triage Bot
      run: |
        if [ -n "${{ inputs.repositories }}" ]; then
          node dist/src/main.js \
            --gh-app-id ${{ inputs.gh-app-id }} \
            --gh-app-installation-id ${{ inputs.gh-app-installation-id }} \
            --gh-app-pem-file private-key.pem \
            --repositories "${{ inputs.repositories }}" \
            ${{ inputs.organization }} ${{ inputs.project-number }}
        else
          node dist/src/main.js \
            --gh-app-id ${{ inputs.gh-app-id }} \
            --gh-app-installation-id ${{ inputs.gh-app-installation-id }} \
            --gh-app-pem-file private-key.pem \
            ${{ inputs.organization }} ${{ inputs.project-number }}
        fi
      shell: bash
      working-directory: ${{ github.action_path }}

    - name: Cleanup private key
      run: rm -f private-key.pem
      shell: bash
      if: ${{ always() }}
      working-directory: ${{ github.action_path }}
