query ($cursor: String) {
 search(type:ISSUE first:50 query:"org:jupyterhub is:pr state:open" after:$cursor){
  nodes {
    ... on PullRequest {
      id,
      url,
      createdAt,
      lastEditedAt,
      deletions,
      additions,
      statusCheckRollup {
        state
      }
      mergeable,
      participants(first:100) {
        nodes {
            login
        }
      }
      reviews(first:100) {
        nodes {
            authorCanPushToRepository,
            isMinimized,
            state
        }
      }
      repository {
        id,
        name,
        owner {
            login
        }
      },
      author {
        login
      },
      title,
    }
  }
  pageInfo {
    hasNextPage
    endCursor
  }
  }
}