query ($cursor: String, $searchQuery: String!) {
 search(type:ISSUE first:30 query:$searchQuery after:$cursor){
  nodes {
    ... on PullRequest {
      id,
      url,
      createdAt,
      lastEditedAt,
      deletions,
      additions,
      statusCheckRollup {
        state
      }
      mergeable,
      participants(first:100) {
        nodes {
            login
        }
      }
      files(first:100) {
        nodes {
            path,
            additions,
            deletions
        }
      }
      reviews(first:100) {
        nodes {
            authorCanPushToRepository,
            isMinimized,
            state
        }
      }
      repository {
        id,
        name,
        owner {
            login
        }
      },
      author {
        login
      },
      title,
    }
  }
  pageInfo {
    hasNextPage
    endCursor
  }
  }
}