---
name: 'PR Triage Board Bot'

on:
  workflow_call:
    inputs:
      organization:
        description: 'GitHub organization name'
        required: true
        type: string
      project-number:
        description: 'GitHub Project board number'
        required: true
        type: string
      gh-app-id:
        description: 'GitHub App ID for authentication'
        required: true
        type: string
      gh-installation-id:
        description: 'GitHub App Installation ID for authentication'
        required: true
        type: string
      repositories:
        description: 'Comma-separated list of repository names to limit querying to (optional)'
        required: false
        type: string
      node-version:
        description: 'Node.js version to use'
        required: false
        type: string
        default: '23.x'
    secrets:
      gh-app-private-key:
        description: 'GitHub App private key (PEM format) for authentication'
        required: true


jobs:
  pr-triage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: ${{ inputs.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Setup GitHub App Private Key
        run: |
          echo "${{ secrets.gh-app-private-key }}" > private-key.pem

      - name: Run PR Triage Bot
        run: |
          if [ -n "${{ inputs.repositories }}" ]; then
            node dist/src/main.js \
              --gh-app-id ${{ inputs.gh-app-id }} \
              --gh-installation-id ${{ inputs.gh-installation-id }} \
              --gh-app-pem-file private-key.pem \
              --repositories "${{ inputs.repositories }}" \
              ${{ inputs.organization }} ${{ inputs.project-number }}
          else
            node dist/src/main.js \
              --gh-app-id ${{ inputs.gh-app-id }} \
              --gh-installation-id ${{ inputs.gh-installation-id }} \
              --gh-app-pem-file private-key.pem \
              ${{ inputs.organization }} ${{ inputs.project-number }}
          fi

      - name: Cleanup private key
        run: rm -f private-key.pem
        if: ${{ always() }}