---
name: Run Bot

on:
  schedule:
    - cron: '13 * * * *'  # Every hour
  workflow_dispatch:  # Allows triggering manually from the UI
  push:
    branches: ["main"]


jobs:
  jupyterhub:
    runs-on: ubuntu-latest
    steps:
      - name: Run JupyterHub PR Triage Bot
        uses: yuvipanda/pr-triage-board-bot@main
        with:
          organization: 'jupyterhub'
          project-number: '4'
          gh-app-id: '1793875'
          gh-app-installation-id: '81302562'
          gh-app-private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
