---
name: Run Bot

on:
  schedule:
    - cron: '13 * * * *'  # Every hour
  workflow_dispatch:  # Allows triggering manually from the UI
  push:
    branches: ["main"]

jobs:
  jupyterhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run JupyterHub PR Triage Bot
        uses: ./
        with:
          organization: 'jupyterhub'
          project-number: '4'
          gh-app-id: '1793875'
          gh-app-installation-id: '81302562'
          gh-app-private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

  jupyterlab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run JupyterLab PR Triage Bot
        uses: ./
        with:
          organization: 'jupyterlab'
          project-number: '11'
          gh-app-id: '1842581'
          gh-app-installation-id: '82755492'
          gh-app-private-key: ${{ secrets.GH_APP_PRIVATE_KEY_JUPYTERLAB }}
