---
name: Run Bot

on:
  schedule:
    - cron: '13 * * * *'  # Every hour
  workflow_dispatch:  # Allows triggering manually from the UI
  push:
    branches: ["main"]

jobs:
  jupyterhub:
    uses: ./.github/workflows/reusable-pr-triage.yml
    with:
      organization: 'jupyterhub'
      project-number: '4'
      gh-app-id: '1793875'
      gh-installation-id: '81302562'
    secrets:
      gh-app-private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

  jupyterlab:
    uses: ./.github/workflows/reusable-pr-triage.yml
    with:
      organization: 'jupyterlab'
      project-number: '11'
      gh-app-id: '1842581'
      gh-installation-id: '82755492'
    secrets:
      gh-app-private-key: ${{ secrets.GH_APP_PRIVATE_KEY_JUPYTERLAB }}
